##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# source-code is the URL of this repo
source-code: https://github.com/LSIS5830-Spring2025/Sandbox_Perez_Nick

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "Iconic Sports Teams"
# tagline, a short phrase in the banner
tagline: a template for creating simple digital exhibits
# description appears in meta tags (keep <160 chars)
description: "A mini‐exhibit of five iconic global sports teams, showcasing logos and basic facts."
# site author (for meta tags)
author: Elikem Des-Amekudi

##########
# COLLECTION SETTINGS
#
# metadata is the basename (no “.csv”) of your file in _data/
metadata: sports_teams

##########
# Site/Organization Branding 
# (uncomment & edit if you have an org logo you’d like to show)
# organization-name: "Your Org Name"
# organization-link: https://your.org.link/
# organization-logo-banner: /assets/images/your-banner.png
# organization-logo-nav: /assets/images/your-nav-logo.png

##########
# ROBOTS EXCLUDE
#
# noindex: true    # uncomment if you do NOT want Google to index

##########
# BUILD SETTINGS 
#
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed

